language: python
cache: pip
arch:
    - amd64
    - arm64
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
env: TOXENV=py

install:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then
      pip install -U "pip==10.0.1"
      PIP_ARGS="-c requirements/3.3/constraints.txt"
    fi
  - pip install -U "tox<3.8.0" $PIP_ARGS
  - if [[ $TOXENV == "py" ]]; then ./ci_tools/retry.sh python updatezinfo.py; fi

script:
  - tox
  - |
    if [[ $TOXENV == "build" ]]; then
      exactly_one() {
        value=$(find dist -iname $1 | wc -l)
        if [ $value -ne 1 ]; then
          echo "Found $value instances of $1, not 1"
          return 1
        else
          echo "Found exactly 1 instance of $value"
        fi
      }

      # Check that exactly one tarball and one wheel are created
      exactly_one '*.tar.gz'
      exactly_one '*.whl'
    fi

after_success:
  - if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
